import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/Navbar";
import { FilteredHotelsProvider } from "@/contex/FilteredHotelContext";
import { ThemeProvider } from "@/contex/ThemeContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Traveloka - Discounts up to 50% Flights, Hotels, Activities",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased relative bg-gray-400`}>
        <ThemeProvider>
          <Navbar />
          <FilteredHotelsProvider>{children}</FilteredHotelsProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
